import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trevor Alpert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full py-6 flex items-center border-b border-gray-700 bg-[#0a2233] mb-8 px-8">
          <Link href="/" className="flex-shrink-0">
            <Image src="/logo.png" alt="Trevor Alpert Logo" width={100} height={100} className="w-full h-full" />
          </Link>
          <nav className="flex-1 flex justify-center gap-20 text-3xl font-semibold text-white">
            <Link href="/" className="hover:text-[#ffe066] transition-colors">Home</Link>
            <Link href="/projects" className="hover:text-[#ffe066] transition-colors">Projects</Link>
            <Link href="/about" className="hover:text-[#ffe066] transition-colors">About</Link>
            <Link href="/contact" className="hover:text-[#ffe066] transition-colors">Contact</Link>
          </nav>
          <div style={{ width: 80 }} aria-hidden="true"></div>
        </header>
        {children}
      </body>
    </html>
  );
}
